# Generated by Django 4.1 on 2022-11-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name',)},
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.place')),
                ('coffee', models.CharField(max_length=150)),
            ],
            bases=('user.place',),
        ),
    ]
