# Generated by Django 4.1 on 2022-11-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_place_alter_person_options_cafe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cafe',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
